export type ActivityEventType =
  | "config_saved"
  | "mods_saved"
  | "marketplace_import"
  | "server_started"
  | "server_stopped"
  | "server_restarted"
  | "safe_restart"
  | "fix_server"
  | "diagnostic_run"
  | "critical_issue_detected"
  | "health_warning"
  | "joinability_check"
  | "config_repaired";

export type ActivityEventSeverity = "info" | "warn" | "error" | "success";

export type ActivityEvent = {
  id: string;
  type: ActivityEventType;
  severity: ActivityEventSeverity;
  title: string;
  message?: string;
  timestamp: string;
  metadata?: Record<string, unknown>;
};

/** Input for recording (id + timestamp generated by store). */
export type ActivityEventInput = Omit<ActivityEvent, "id" | "timestamp">;
